name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: '${{ github.event.repository.name }}'

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.10
        with:
          configurationFile: renovate.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT_ENABLED: 'true'
